DROP TABLE IF EXISTS schema_version;
DROP TABLE IF EXISTS porto;
DROP TABLE IF EXISTS filial;
DROP TABLE IF EXISTS endereco;
DROP TABLE IF EXISTS municipio;
DROP TABLE IF EXISTS estado;
DROP TABLE IF EXISTS pais;