INSERT INTO municipio (id, nome, id_estado) VALUES (1,'Brasiléia',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (2,'Capixaba',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (3,'Epitaciolândia',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (4,'Feijó',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (5,'Mâncio Lima',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (6,'Marechal Thaumaturgo',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (7,'Porto Acre',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (8,'Porto Walter',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (9,'Rodrigues Alves',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (10,'Sena Madureira',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (11,'Tarauacá',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (12,'Xapuri',1);
INSERT INTO municipio (id, nome, id_estado) VALUES (13,'Anadia',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (14,'Atalaia',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (15,'Barra De São Miguel',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (16,'Batalha',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (17,'Belo Monte',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (18,'Branquinha',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (19,'Cacimbinhas',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (20,'Campestre',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (21,'Campo Grande',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (22,'Capela',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (23,'Carneiros',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (24,'Coité Do Nóia',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (25,'Coqueiro Seco',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (26,'Craíbas',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (27,'Dois Riachos',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (28,'Estrela De Alagoas',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (29,'Feliz Deserto',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (30,'Girau Do Ponciano',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (31,'Ibateguara',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (32,'Igreja Nova',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (33,'Jacaré Dos Homens',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (34,'Japaratinga',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (35,'Jequiá Da Praia',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (36,'Joaquim Gomes',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (37,'Junqueiro',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (38,'Limoeiro De Anadia',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (39,'Major Isidoro',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (40,'Mar Vermelho',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (41,'Maravilha',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (42,'Maribondo',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (43,'Matriz De Camaragibe',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (44,'Messias',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (45,'Monteirópolis',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (46,'Novo Lino',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (47,'Olho D`Água Do Casado',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (48,'Olho D`Água Grande',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (49,'Ouro Branco',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (50,'Palmeira Dos Índios',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (51,'Pariconha',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (52,'Paripueira',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (53,'Paulo Jacinto',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (54,'Piaçabuçu',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (55,'Pilar',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (56,'Piranhas',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (57,'Porto Calvo',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (58,'Porto Real Do Colégio',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (59,'Quebrangulo',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (60,'Roteiro',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (61,'Santana Do Ipanema',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (62,'Santana Do Mundaú',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (63,'São José Da Laje',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (64,'São Luís Do Quitunde',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (65,'São Miguel Dos Campos',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (66,'São Sebastião',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (67,'Satuba',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (68,'Tanque D`Arca',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (69,'Teotônio Vilela',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (70,'Traipu',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (71,'Viçosa',2);
INSERT INTO municipio (id, nome, id_estado) VALUES (72,'Amaturá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (73,'Princesa Isabel',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (74,'Apuí',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (75,'Autazes',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (76,'Barcelos',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (77,'Benjamin Constant',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (78,'Boa Vista Do Ramos',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (79,'Borba',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (80,'Canutama',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (81,'Carauari',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (82,'Careiro Da Várzea',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (83,'Codajás',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (84,'Envira',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (85,'Guajará',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (86,'Humaitá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (87,'Iranduba',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (88,'Itamarati',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (89,'Japurá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (90,'Jutaí',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (91,'Lábrea',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (92,'Manaquiri',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (93,'Manicoré',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (94,'Maués',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (95,'Nhamundá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (96,'Novo Airão',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (97,'Parintins',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (98,'Pauini',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (99,'Rio Preto Da Eva',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (100,'Santo Antônio Do Içá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (101,'São Paulo De Olivença',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (102,'São Sebastião Do Uatumã',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (103,'Silves',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (104,'Tapauá',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (105,'Tonantins',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (106,'Urucará',3);
INSERT INTO municipio (id, nome, id_estado) VALUES (107,'Amapá',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (108,'Calçoene',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (109,'Ferreira Gomes',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (110,'Laranjal Do Jari',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (111,'Mazagão',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (112,'Pedra Branca Do Amaparí',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (113,'Pracuúba',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (114,'Santana',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (115,'Tartarugalzinho',4);
INSERT INTO municipio (id, nome, id_estado) VALUES (116,'Abaíra',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (117,'Abaré',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (118,'Adustina',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (119,'Aiquara',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (120,'Alcobaça',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (121,'Almadina',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (122,'Amélia Rodrigues',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (123,'Anagé',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (124,'Andorinha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (125,'Angical',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (126,'Antas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (127,'Antônio Gonçalves',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (128,'Apuarema',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (129,'Araças',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (130,'Araci',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (131,'Arataca',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (132,'Aurelino Leal',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (133,'Baixa Grande',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (134,'Banzaê',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (135,'Barra Da Estiva',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (136,'Barra Do Mendes',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (137,'Barra Do Rocha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (138,'Barro Alto',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (139,'Barro Preto',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (140,'Belo Campo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (141,'Biritinga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (142,'Boa Vista Do Tupim',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (143,'Bom Jesus Da Serra',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (144,'Bonito',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (145,'Boquira',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (146,'Brejões',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (147,'Quixabá',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (148,'Brumado',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (149,'Buritirama',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (150,'Cabaceiras Do Paraguaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (151,'Caculé',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (152,'Caém',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (153,'Caetité',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (154,'Cairu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (155,'Camacan',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (156,'Camaçari',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (157,'Campo Formoso',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (158,'Canápolis',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (159,'Canavieiras',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (160,'Candeal',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (161,'Candiba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (162,'Cansanção',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (163,'Capela Do Alto Alegre',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (164,'Caraíbas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (165,'Caravelas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (166,'Carinhanha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (167,'Castro Alves',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (168,'Catolândia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (169,'Caturama',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (170,'Chorrochó',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (171,'Cipó',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (172,'Coaraci',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (173,'Conceição Da Feira',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (174,'Conceição Do Coité',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (175,'Conde',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (176,'Condeúba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (177,'Coração De Maria',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (178,'Cordeiros',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (179,'Coronel João Sá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (180,'Cotegipe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (181,'Crisópolis',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (182,'Cristópolis',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (183,'Curaçá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (184,'Dias D`Ávila',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (185,'Dom Basílio',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (186,'Elísio Medrado',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (187,'Entre Rios',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (188,'Esplanada',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (189,'Euclides Da Cunha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (190,'Fátima',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (191,'Feira De Santana',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (192,'Filadélfia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (193,'Floresta Azul',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (194,'Gandu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (195,'Gavião',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (196,'Glória',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (197,'Governador Mangabeira',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (198,'Guajeru',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (199,'Guaratinga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (200,'Iaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (201,'Ibicaraí',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (202,'Ibicuí',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (203,'Ibipeba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (204,'Ibiquera',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (205,'Ibirapuã',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (206,'Ibitiara',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (207,'Ibititá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (208,'Ichu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (209,'Igrapiúna',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (210,'Ilhéus',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (211,'Ipecaetá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (212,'Ipiaú',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (213,'Ipupiara',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (214,'Iramaia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (215,'Irará',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (216,'Irecê',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (217,'Itaberaba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (218,'Itacaré',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (219,'Itagi',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (220,'Itagimirim',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (221,'Itajuípe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (222,'Itamari',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (223,'Itanagra',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (224,'Itanhém',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (225,'Itapé',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (226,'Itapetinga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (227,'Itapitanga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (228,'Itarantim',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (229,'Itatim',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (230,'Itiúba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (231,'Ituaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (232,'Iuiú',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (233,'Jacaraci',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (234,'Jacobina',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (235,'Jaguarari',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (236,'Jandaíra',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (237,'Jeremoabo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (238,'Jiquiriçá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (239,'Juazeiro',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (240,'Jucuruçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (241,'Jussari',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (242,'Jussiape',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (243,'Lagoa Real',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (244,'Lajedão',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (245,'Lajedo Do Tabocal',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (246,'Lamarão',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (247,'Lauro De Freitas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (248,'Licínio De Almeida',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (249,'Luís Eduardo Magalhães',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (250,'Macajuba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (251,'Macaúbas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (252,'Madre De Deus',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (253,'Maiquinique',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (254,'Malhada',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (255,'Manoel Vitorino',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (256,'Mansidão',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (257,'Maragogipe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (258,'Marcionílio Souza',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (259,'Mata De São João',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (260,'Matina',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (261,'Miguel Calmon',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (262,'Mirangaba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (263,'Mirante',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (264,'Morpará',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (265,'Mortugaba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (266,'Mucuri',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (267,'Mundo Novo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (268,'Muniz Ferreira',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (269,'Muritiba',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (270,'Mutuípe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (271,'Nilo Peçanha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (272,'Nova Canaã',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (273,'Nova Ibiá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (274,'Nova Redenção',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (275,'Nova Soure',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (276,'Novo Horizonte',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (277,'Olindina',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (278,'Ouriçangas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (279,'Ourolândia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (280,'Palmeiras',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (281,'Paramirim',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (282,'Paripiranga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (283,'Paulo Afonso',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (284,'Pedrão',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (285,'Piatã',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (286,'Pilão Arcado',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (287,'Pindobaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (288,'Piraí Do Norte',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (289,'Piripá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (290,'Planaltino',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (291,'Poções',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (292,'Ponto Novo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (293,'Potiraguá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (294,'Prado',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (295,'Presidente Tancredo Neves',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (296,'Queimadas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (297,'Quixabeira',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (298,'Remanso',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (299,'Riachão Das Neves',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (300,'Riacho De Santana',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (301,'Ribeira Do Amparo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (302,'Ribeirão Do Largo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (303,'Rio De Contas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (304,'Rio Do Pires',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (305,'Rodelas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (306,'Ruy Barbosa',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (307,'Salvador',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (308,'Santa Brígida',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (309,'Santa Cruz Da Vitória',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (310,'Santa Inês',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (311,'Santa Maria Da Vitória',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (312,'Santa Teresinha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (313,'Santaluz',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (314,'Santanópolis',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (315,'Santo Antônio De Jesus',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (316,'São Desidério',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (317,'São Felipe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (318,'São Félix',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (319,'São Francisco Do Conde',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (320,'São Gonçalo Dos Campos',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (321,'São José Do Jacuípe',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (322,'São Miguel Das Matas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (323,'Sapeaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (324,'Sátiro Dias',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (325,'Saúde',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (326,'Sebastião Laranjeiras',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (327,'Sento Sé',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (328,'Serra Do Ramalho',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (329,'Serra Preta',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (330,'Serrinha',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (331,'Simões Filho',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (332,'Sítio Do Quinto',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (333,'Souto Soares',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (334,'Tanhaçu',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (335,'Tanque Novo',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (336,'Taperoá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (337,'Teixeira De Freitas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (338,'Teofilândia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (339,'Teolândia',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (340,'Tremedal',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (341,'Uauá',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (342,'Ubaíra',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (343,'Ubatã',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (344,'Umburanas',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (345,'Urandi',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (346,'Utinga',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (347,'Valente',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (348,'Várzea Da Roça',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (349,'Várzea Nova',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (350,'Vera Cruz',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (351,'Vitória Da Conquista',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (352,'Wagner',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (353,'Xique Xique',5);
INSERT INTO municipio (id, nome, id_estado) VALUES (354,'Abaiara',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (355,'Acarape',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (356,'Acopiara',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (357,'Alcântaras',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (358,'Alto Santo',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (359,'Antonina Do Norte',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (360,'Apuiarés',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (361,'Aracati',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (362,'Ararendá',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (363,'Aratuba',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (364,'Arneiroz',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (365,'Aurora',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (366,'Banabuiú',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (367,'Riachão',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (368,'Barreira',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (369,'Barroquinha',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (370,'Beberibe',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (371,'Boa Viagem',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (372,'Brejo Santo',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (373,'Campos Sales',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (374,'Capistrano',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (375,'Cariré',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (376,'Cariús',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (377,'Carnaubal',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (378,'Catarina',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (379,'Caucaia',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (380,'Chaval',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (381,'Choró',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (382,'Coreaú',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (383,'Crato',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (384,'Cruz',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (385,'Ererê',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (386,'Eusébio',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (387,'Forquilha',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (388,'Fortim',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (389,'Frecheirinha',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (390,'Graça',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (391,'Granjeiro',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (392,'Guaiúba',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (393,'Guaraciaba Do Norte',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (394,'Hidrolândia',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (395,'Ibaretama',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (396,'Ibicuitinga',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (397,'Icapuí',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (398,'Iguatu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (399,'Ipaporanga',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (400,'Ipu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (401,'Ipueiras',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (402,'Irauçuba',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (403,'Itaitinga',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (404,'Itapipoca',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (405,'Itapiúna',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (406,'Itatira',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (407,'Jaguaribara',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (408,'Jaguaruana',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (409,'Jardim',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (410,'Juazeiro Do Norte',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (411,'Jucás',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (412,'Limoeiro Do Norte',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (413,'Madalena',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (414,'Maranguape',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (415,'Martinópole',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (416,'Mauriti',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (417,'Meruoca',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (418,'Milhã',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (419,'Missão Velha',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (420,'Monsenhor Tabosa',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (421,'Morada Nova',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (422,'Morrinhos',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (423,'Mulungu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (424,'Nova Russas',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (425,'Ocara',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (426,'Orós',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (427,'Pacatuba',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (428,'Pacujá',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (429,'Palhano',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (430,'Paracuru',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (431,'Parambu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (432,'Pedra Branca',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (433,'Pentecoste',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (434,'Pindoretama',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (435,'Pires Ferreira',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (436,'Poranga',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (437,'Potengi',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (438,'Quiterianópolis',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (439,'Quixelô',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (440,'Quixeré',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (441,'Redenção',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (442,'Riacho De Santo Antônio',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (443,'Salitre',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (444,'Santana Do Acaraú',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (445,'São Benedito',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (446,'São Gonçalo Do Amarante',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (447,'São Luís Do Curu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (448,'Senador Pompeu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (449,'Sobral',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (450,'Tabuleiro Do Norte',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (451,'Tarrafas',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (452,'Tauá',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (453,'Tianguá',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (454,'Tururu',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (455,'Umari',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (456,'Umirim',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (457,'Uruoca',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (458,'Várzea Alegre',6);
INSERT INTO municipio (id, nome, id_estado) VALUES (459,'Brasília',7);
INSERT INTO municipio (id, nome, id_estado) VALUES (460,'Água Doce Do Norte',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (461,'Águia Branca',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (462,'Alfredo Chaves',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (463,'Anchieta',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (464,'Apiacá',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (465,'Baixo Guandu',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (466,'Barra De São Francisco',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (467,'Bom Jesus Do Norte',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (468,'Brejetuba',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (469,'Cariacica',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (470,'Colatina',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (471,'Conceição Do Castelo',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (472,'Divino De São Lourenço',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (473,'Dores Do Rio Preto',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (474,'Ecoporanga',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (475,'Guaçuí',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (476,'Guarapari',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (477,'Ibiraçu',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (478,'Ibitirama',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (479,'Irupi',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (480,'Itapemirim',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (481,'Iúna',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (482,'Jaguaré',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (483,'João Neiva',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (484,'Linhares',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (485,'Marataízes',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (486,'Marechal Floriano',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (487,'Mimoso Do Sul',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (488,'Mucurici',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (489,'Muqui',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (490,'Nova Venécia',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (491,'Pedro Canário',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (492,'Piúma',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (493,'Ponto Belo',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (494,'Rio Bananal',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (495,'Santa Leopoldina',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (496,'Santa Teresa',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (497,'São Domingos Do Norte',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (498,'São José Do Calçado',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (499,'São Mateus',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (500,'Serra',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (501,'Sooretama',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (502,'Venda Nova Do Imigrante',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (503,'Vila Pavão',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (504,'Vila Velha',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (505,'Vitória',8);
INSERT INTO municipio (id, nome, id_estado) VALUES (506,'Abadiânia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (507,'Adelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (508,'Água Limpa',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (509,'Águas Lindas De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (510,'Aloândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (511,'Alto Paraíso De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (512,'Alvorada Do Norte',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (513,'Americano Do Brasil',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (514,'Anápolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (515,'Salgadinho',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (516,'Aparecida Do Rio Doce',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (517,'Aporé',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (518,'Aragarças',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (519,'Araguapaz',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (520,'Aruanã',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (521,'Aurilândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (522,'Baliza',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (523,'Bela Vista De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (524,'Bom Jesus De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (525,'Bonfinópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (526,'Brazabrantes',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (527,'Buriti Alegre',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (528,'Buritinópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (529,'Cabeceiras',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (530,'Cachoeira De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (531,'Caçu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (532,'Caiapônia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (533,'Caldazinha',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (534,'Campinaçu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (535,'Campinorte',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (536,'Campo Limpo De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (537,'Campos Verdes',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (538,'Castelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (539,'Catalão',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (540,'Cavalcante',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (541,'Ceres',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (542,'Chapadão Do Céu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (543,'Cocalzinho De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (544,'Córrego Do Ouro',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (545,'Corumbá De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (546,'Cristalina',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (547,'Crixás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (548,'Cumari',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (549,'Damianópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (550,'Davinópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (551,'Divinópolis De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (552,'Edealina',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (553,'Edéia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (554,'Faina',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (555,'Firminópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (556,'Formosa',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (557,'Formoso',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (558,'Goianápolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (559,'Goiandira',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (560,'Goiânia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (561,'Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (562,'Gouvelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (563,'Guapó',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (564,'Guarani De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (565,'Heitoraí',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (566,'Hidrolina',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (567,'Iaciara',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (568,'Indiara',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (569,'Ipameri',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (570,'Iporá',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (571,'Israelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (572,'Itaguari',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (573,'Itajá',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (574,'Itapirapuã',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (575,'Itapuranga',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (576,'Itauçu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (577,'Ivolândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (578,'Jaraguá',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (579,'Jaupaci',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (580,'Jesúpolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (581,'Jussara',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (582,'Leopoldo De Bulhões',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (583,'Mairipotaba',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (584,'Mara Rosa',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (585,'Marzagão',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (586,'Maurilândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (587,'Minaçu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (588,'Moiporá',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (589,'Ipojuca',16);
INSERT INTO municipio (id, nome, id_estado) VALUES (590,'Montes Claros De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (591,'Montividiu Do Norte',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (592,'Morro Agudo De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (593,'Mossâmedes',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (594,'Mundo Novo',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (595,'Nazário',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (596,'Nerópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (597,'Nova América',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (598,'Nova Crixás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (599,'Nova Iguaçu De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (600,'Nova Roma',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (601,'Novo Brasil',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (602,'Novo Planalto',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (603,'Ouro Verde De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (604,'Padre Bernardo',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (605,'Palmeiras De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (606,'Palmelo',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (607,'Panamá',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (608,'Paraúna',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (609,'Perolândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (610,'Pilar De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (611,'Piranhas',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (612,'Pires Do Rio',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (613,'Planaltina',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (614,'Porangatu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (615,'Portelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (616,'Posse',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (617,'Quirinópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (618,'Rianápolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (619,'Rio Verde',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (620,'Rubiataba',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (621,'Santa Bárbara De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (622,'Santa Fé De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (623,'Santa Isabel',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (624,'Santa Rita Do Araguaia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (625,'Santa Rosa De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (626,'Santa Terezinha De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (627,'Santo Antônio Da Barra',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (628,'Santo Antônio Do Descoberto',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (629,'São Domingos',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (630,'São João D`Aliança',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (631,'São Luís De Montes Belos',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (632,'São Luíz Do Norte',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (633,'São Miguel Do Passa Quatro',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (634,'São Patrício',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (635,'Senador Canedo',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (636,'Silvânia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (637,'Simolândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (638,'Taquaral De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (639,'Terezópolis De Goiás',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (640,'Trindade',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (641,'Trombas',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (642,'Turvelândia',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (643,'Uruaçu',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (644,'Urutaí',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (645,'Varjão',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (646,'Vianópolis',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (647,'Vila Boa',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (648,'Vila Propício',9);
INSERT INTO municipio (id, nome, id_estado) VALUES (649,'Afonso Cunha',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (650,'Alcântara',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (651,'Aldeias Altas',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (652,'Alto Alegre Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (653,'Alto Parnaíba',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (654,'Amapá Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (655,'Anajatuba',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (656,'Anapurus',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (657,'Araguanã',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (658,'Arame',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (659,'Axixá',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (660,'Bacabal',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (661,'Balsas',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (662,'Barra Do Corda',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (663,'Bela Vista Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (664,'Belágua',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (665,'Bequimão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (666,'Boa Vista Do Gurupi',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (667,'Bom Jardim',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (668,'Bom Lugar',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (669,'Brejo De Areia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (670,'Buriti',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (671,'Buriticupu',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (672,'Cachoeira Grande',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (673,'Cajari',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (674,'Cândido Mendes',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (675,'Cantanhede',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (676,'Carolina',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (677,'Carutapera',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (678,'Cedral',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (679,'Centro Do Guilherme',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (680,'Chapadinha',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (681,'Cidelândia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (682,'Coelho Neto',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (683,'Conceição Do Lago Açu',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (684,'Coroatá',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (685,'Davinópolis',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (686,'Duque Bacelar',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (687,'Estreito',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (688,'Fernando Falcão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (689,'Formosa Da Serra Negra',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (690,'Fortuna',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (691,'Godofredo Viana',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (692,'Governador Archer',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (693,'Governador Eugênio Barros',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (694,'Governador Newton Bello',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (695,'Governador Nunes Freire',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (696,'Grajaú',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (697,'Guimarães',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (698,'Icatu',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (699,'Igarapé Grande',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (700,'Imperatriz',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (701,'Itapecuru Mirim',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (702,'Jatobá',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (703,'João Lisboa',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (704,'Joselândia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (705,'Lago Da Pedra',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (706,'Lago Dos Rodrigues',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (707,'Lago Verde',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (708,'Lagoa Grande Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (709,'Lima Campos',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (710,'Loreto',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (711,'Magalhães De Almeida',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (712,'Marajá Do Sena',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (713,'Mata Roma',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (714,'Matinha',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (715,'Matões Do Norte',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (716,'Mirador',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (717,'Miranda Do Norte',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (718,'Monção',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (719,'Morros',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (720,'Nina Rodrigues',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (721,'Nova Iorque',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (722,'Olho D`Água Das Cunhãs',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (723,'Paço Do Lumiar',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (724,'Palmeirândia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (725,'Parnarama',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (726,'Passagem Franca',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (727,'Paulino Neves',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (728,'Pedreiras',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (729,'Penalva',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (730,'Peri Mirim',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (731,'Pindaré Mirim',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (732,'Pio Xii',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (733,'Porto Franco',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (734,'Porto Rico Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (735,'Presidente Juscelino',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (736,'Presidente Sarney',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (737,'Presidente Vargas',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (738,'Raposa',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (739,'Ribamar Fiquene',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (740,'Rosário',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (741,'Santa Helena',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (742,'Santa Inês',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (743,'Santa Luzia Do Paruá',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (744,'Santa Rita',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (745,'Santana Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (746,'Santo Antônio Dos Lopes',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (747,'São Bento',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (748,'São Bernardo',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (749,'São Domingos Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (750,'São Félix De Balsas',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (751,'São Francisco Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (752,'São João Do Carú',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (753,'São João Do Soter',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (754,'São João Dos Patos',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (755,'São José Dos Basílios',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (756,'São Luís',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (757,'São Mateus Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (758,'São Pedro Da Água Branca',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (759,'São Raimundo Das Mangabeiras',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (760,'São Roberto',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (761,'São Vicente Ferrer',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (762,'Senador Alexandre Costa',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (763,'Serrano Do Maranhão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (764,'Sítio Novo',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (765,'Sucupira Do Riachão',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (766,'Timbiras',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (767,'Timon',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (768,'Tufilândia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (769,'Turiaçu',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (770,'Turilândia',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (771,'Urbano Santos',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (772,'Viana',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (773,'Vitória Do Mearim',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (774,'Vitorino Freire',10);
INSERT INTO municipio (id, nome, id_estado) VALUES (775,'Abadia Dos Dourados',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (776,'Abre Campo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (777,'Açucena',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (778,'Água Boa',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (779,'Aguanil',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (780,'Águas Vermelhas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (781,'Aiuruoca',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (782,'Alagoa',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (783,'Além Paraíba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (784,'Alfredo Vasconcelos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (785,'Alpercata',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (786,'Alterosa',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (787,'Alto Caparaó',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (788,'Alto Rio Doce',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (789,'Alvinópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (790,'Amparo Do Serra',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (791,'Andradas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (792,'Angelândia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (793,'Antônio Dias',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (794,'Araçaí',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (795,'Aracitaba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (796,'Araguari',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (797,'Arantina',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (798,'Araporã',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (799,'Araújos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (800,'Arceburgo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (801,'Areado',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (802,'Argirita',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (803,'Arinos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (804,'Santa Cecília',15);
INSERT INTO municipio (id, nome, id_estado) VALUES (805,'Augusto De Lima',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (806,'Baependi',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (807,'Bambuí',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (808,'Bandeira Do Sul',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (809,'Barão De Monte Alto',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (810,'Barbacena',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (811,'Barroso',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (812,'Belmiro Braga',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (813,'Belo Oriente',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (814,'Belo Vale',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (815,'Berizal',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (816,'Betim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (817,'Bicas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (818,'Biquinhas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (819,'Bocaina De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (820,'Bom Despacho',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (821,'Bom Jesus Da Penha',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (822,'Bom Jesus Do Amparo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (823,'Bom Repouso',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (824,'Bonfim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (825,'Bonito De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (826,'Borda Da Mata',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (827,'Botumirim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (828,'Brasilândia De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (829,'Brasópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (830,'Braúnas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (831,'Bueno Brandão',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (832,'Bugre',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (833,'Buritis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (834,'Cabeceira Grande',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (835,'Cachoeira Da Prata',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (836,'Cachoeira De Pajeú',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (837,'Caetanópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (838,'Caeté',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (839,'Cajuri',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (840,'Camacho',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (841,'Camanducaia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (842,'Cambuquira',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (843,'Campanha',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (844,'Campina Verde',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (845,'Campo Belo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (846,'Campo Florido',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (847,'Campos Altos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (848,'Cana Verde',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (849,'CanÁpolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (850,'Candeias',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (851,'Caparaó',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (852,'Capelinha',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (853,'Capim Branco',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (854,'Capitão Andrade',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (855,'Capitólio',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (856,'Caputira',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (857,'Caranaíba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (858,'Carangola',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (859,'Carbonita',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (860,'Careaçu',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (861,'Carmésia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (862,'Carmo Da Mata',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (863,'Carmo Do Cajuru',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (864,'Carmo Do Paranaíba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (865,'Carmópolis De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (866,'Carneirinho',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (867,'Carvalhópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (868,'Casa Grande',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (869,'CÁssia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (870,'Cataguases',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (871,'Catuji',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (872,'Catuti',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (873,'Cedro Do Abaeté',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (874,'Central De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (875,'ChÁcara',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (876,'Chapada Do Norte',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (877,'Itacuruba',16);
INSERT INTO municipio (id, nome, id_estado) VALUES (878,'Cipotânea',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (879,'Claro Dos Poções',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (880,'Coimbra',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (881,'Comendador Gomes',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (882,'Conceição Da Aparecida',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (883,'Conceição Das Alagoas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (884,'Conceição Das Pedras',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (885,'Conceição Do Mato Dentro',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (886,'Conceição Do ParÁ',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (887,'Conceição Dos Ouros',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (888,'Confins',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (889,'Congonhal',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (890,'Congonhas Do Norte',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (891,'Conselheiro Lafaiete',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (892,'Consolação',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (893,'Contagem',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (894,'Coração De Jesus',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (895,'Cordislândia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (896,'Corinto',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (897,'Coromandel',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (898,'Coronel Murta',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (899,'Coronel Xavier Chaves',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (900,'Córrego Danta',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (901,'Córrego Fundo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (902,'Couto De Magalhães De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (903,'Crisólita',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (904,'CristÁlia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (905,'Cristina',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (906,'Cruzeiro Da Fortaleza',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (907,'Cruzília',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (908,'Curral De Dentro',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (909,'Datas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (910,'Delfinópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (911,'Delta',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (912,'Desterro De Entre Rios',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (913,'Diamantina',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (914,'Dionísio',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (915,'Divinésia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (916,'Divino Das Laranjeiras',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (917,'Divinópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (918,'Divisa Alegre',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (919,'Divisópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (920,'Dom Bosco',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (921,'Dom Joaquim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (922,'Dom Viçoso',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (923,'Dores De Campos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (924,'Dores De Guanhães',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (925,'Dores Do Turvo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (926,'Doresópolis',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (927,'Durandé',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (928,'Engenheiro Caldas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (929,'Entre Folhas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (930,'Entre Rios De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (931,'Esmeraldas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (932,'Espinosa',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (933,'Estiva',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (934,'Estrela Dalva',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (935,'Estrela Do Sul',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (936,'Ewbank Da Câmara',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (937,'Extrema',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (938,'Faria Lemos',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (939,'Felisburgo',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (940,'Felixlândia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (941,'Ferros',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (942,'Florestal',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (943,'Formoso',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (944,'Fortaleza De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (945,'Francisco Badaró',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (946,'Francisco SÁ',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (947,'Frei Gaspar',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (948,'Frei Inocêncio',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (949,'Itambé',16);
INSERT INTO municipio (id, nome, id_estado) VALUES (950,'Fruta De Leite',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (951,'Frutal',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (952,'Galiléia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (953,'Glaucilândia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (954,'Goiabeira',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (955,'Gonçalves',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (956,'Gouveia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (957,'Grão Mogol',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (958,'Grupiara',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (959,'Guapé',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (960,'Guaraciama',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (961,'Guarani',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (962,'GuararÁ',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (963,'Guaxupé',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (964,'Guimarânia',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (965,'Gurinhatã',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (966,'Iapu',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (967,'Ibertioga',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (968,'Ibiaí',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (969,'Ibiraci',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (970,'Ibitiúra De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (971,'Icaraí De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (972,'Igarapé',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (973,'Iguatama',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (974,'Ilicínea',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (975,'Inconfidentes',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (976,'Indaiabira',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (977,'Ingaí',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (978,'Inhaúma',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (979,'Ipaba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (980,'Ipanema',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (981,'Ipiaçu',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (982,'Iraí De Minas',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (983,'Itabirinha',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (984,'Itabirito',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (985,'Itacarambi',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (986,'Itaipé',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (987,'Itamarandiba',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (988,'Itambacuri',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (989,'Itamogi',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (990,'Itamonte',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (991,'Itanhomi',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (992,'Itaobim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (993,'Itapecerica',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (994,'Itatiaiuçu',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (995,'Itaúna',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (996,'Itaverava',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (997,'Itueta',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (998,'Itumirim',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (999,'Itutinga',11);
INSERT INTO municipio (id, nome, id_estado) VALUES (1000,'Jacinto',11);