INSERT INTO estado (id, id_pais, nome, sigla) VALUES (1, 1, 'Acre', 'AC');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (2, 1, 'Alagoas', 'AL');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (3, 1, 'Amazonas', 'AM');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (4, 1, 'Amapá', 'AP');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (5, 1, 'Bahia', 'BA');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (6, 1, 'Ceará', 'CE');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (7, 1, 'Distrito Federal', 'DF');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (8, 1, 'Espirito Santo', 'ES');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (9, 1, 'Goiás', 'GO');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (10, 1, 'Maranhão', 'MA');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (11, 1, 'Minas Gerais', 'MG');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (12, 1, 'Mato Grosso do Sul', 'MS');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (13, 1, 'Mato Grosso', 'MT');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (14, 1, 'Pará', 'PA');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (15, 1, 'Paraíba', 'PB');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (16, 1, 'Pernambuco', 'PE');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (17, 1, 'Piauí', 'PI');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (18, 1, 'Paraná', 'PR');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (19, 1, 'Rio de Janeiro', 'RJ');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (20, 1, 'Rio Grande do Norte', 'RN');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (21, 1, 'Rondônia', 'RO');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (22, 1, 'Roraima', 'RR');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (23, 1, 'Rio Grande do Sul', 'RS');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (24, 1, 'Santa Catarina', 'SC');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (25, 1, 'Sergipe', 'SE');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (26, 1, 'São Paulo', 'SP');
INSERT INTO estado (id, id_pais, nome, sigla) VALUES (27, 1, 'Tocantins', 'TO');